graph LR
  藝術_E_Ⅱ_1["藝術/E-Ⅱ-1<br/>(II/content)"]
  藝術_E_Ⅱ_2["藝術/E-Ⅱ-2<br/>(II/content)"]
  藝術_E_Ⅱ_3["藝術/E-Ⅱ-3<br/>(II/content)"]
  藝術_E_Ⅱ_4["藝術/E-Ⅱ-4<br/>(II/content)"]
  藝術_E_Ⅱ_5["藝術/E-Ⅱ-5<br/>(II/content)"]
  藝術_A_Ⅱ_1["藝術/A-Ⅱ-1<br/>(II/content)"]
  藝術_A_Ⅱ_2["藝術/A-Ⅱ-2<br/>(II/content)"]
  藝術_A_Ⅱ_3["藝術/A-Ⅱ-3<br/>(II/content)"]
  藝術_P_Ⅱ_1["藝術/P-Ⅱ-1<br/>(II/content)"]
  藝術_P_Ⅱ_2["藝術/P-Ⅱ-2<br/>(II/content)"]
  藝術_P_Ⅱ_3["藝術/P-Ⅱ-3<br/>(II/content)"]
  藝術_P_Ⅱ_4["藝術/P-Ⅱ-4<br/>(II/content)"]
  藝術_E_Ⅲ_1["藝術/E-Ⅲ-1<br/>(III/content)"]
  藝術_E_Ⅲ_2["藝術/E-Ⅲ-2<br/>(III/content)"]
  藝術_E_Ⅲ_3["藝術/E-Ⅲ-3<br/>(III/content)"]
  藝術_E_Ⅲ_4["藝術/E-Ⅲ-4<br/>(III/content)"]
  藝術_E_Ⅲ_5["藝術/E-Ⅲ-5<br/>(III/content)"]
  藝術_A_Ⅲ_1["藝術/A-Ⅲ-1<br/>(III/content)"]
  藝術_A_Ⅲ_2["藝術/A-Ⅲ-2<br/>(III/content)"]
  藝術_A_Ⅲ_3["藝術/A-Ⅲ-3<br/>(III/content)"]
  藝術_P_Ⅲ_1["藝術/P-Ⅲ-1<br/>(III/content)"]
  藝術_P_Ⅲ_2["藝術/P-Ⅲ-2<br/>(III/content)"]
  藝術_P_Ⅲ_3["藝術/P-Ⅲ-3<br/>(III/content)"]
  藝術_P_Ⅲ_4["藝術/P-Ⅲ-4<br/>(III/content)"]
  藝術_E_Ⅳ_1["藝術/E-Ⅳ-1<br/>(IV/content)"]
  藝術_E_Ⅳ_2["藝術/E-Ⅳ-2<br/>(IV/content)"]
  藝術_E_Ⅳ_3["藝術/E-Ⅳ-3<br/>(IV/content)"]
  藝術_E_Ⅳ_4["藝術/E-Ⅳ-4<br/>(IV/content)"]
  藝術_E_Ⅳ_5["藝術/E-Ⅳ-5<br/>(IV/content)"]
  藝術_A_Ⅳ_1["藝術/A-Ⅳ-1<br/>(IV/content)"]
  藝術_A_Ⅳ_2["藝術/A-Ⅳ-2<br/>(IV/content)"]
  藝術_A_Ⅳ_3["藝術/A-Ⅳ-3<br/>(IV/content)"]
  藝術_P_Ⅳ_1["藝術/P-Ⅳ-1<br/>(IV/content)"]
  藝術_P_Ⅳ_2["藝術/P-Ⅳ-2<br/>(IV/content)"]
  藝術_P_Ⅳ_3["藝術/P-Ⅳ-3<br/>(IV/content)"]
  藝術_P_Ⅳ_4["藝術/P-Ⅳ-4<br/>(IV/content)"]
  藝術_E_V_1["藝術/E-V-1<br/>(V/content)"]
  藝術_E_V_2["藝術/E-V-2<br/>(V/content)"]
  藝術_E_V_3["藝術/E-V-3<br/>(V/content)"]
  藝術_E_V_4["藝術/E-V-4<br/>(V/content)"]
  藝術_E_V_5["藝術/E-V-5<br/>(V/content)"]
  藝術_A_V_1["藝術/A-V-1<br/>(V/content)"]
  藝術_A_V_2["藝術/A-V-2<br/>(V/content)"]
  藝術_A_V_3["藝術/A-V-3<br/>(V/content)"]
  藝術_A_V_4["藝術/A-V-4<br/>(V/content)"]
  藝術_A_V_5["藝術/A-V-5<br/>(V/content)"]
  藝術_P_V_1["藝術/P-V-1<br/>(V/content)"]
  藝術_P_V_2["藝術/P-V-2<br/>(V/content)"]
  藝術_P_V_3["藝術/P-V-3<br/>(V/content)"]
  藝術_P_V_4["藝術/P-V-4<br/>(V/content)"]
  藝術_E_V_6["藝術/E-V-6<br/>(V/content)"]
  藝術_A_V_6["藝術/A-V-6<br/>(V/content)"]
  藝術_P_V_5["藝術/P-V-5<br/>(V/content)"]
  藝術_P_V_6["藝術/P-V-6<br/>(V/content)"]
  藝術_1_Ⅱ_1["藝術/1-Ⅱ-1<br/>(II/performance)"]
  藝術_1_Ⅱ_2["藝術/1-Ⅱ-2<br/>(II/performance)"]
  藝術_1_Ⅱ_3["藝術/1-Ⅱ-3<br/>(II/performance)"]
  藝術_1_Ⅱ_4["藝術/1-Ⅱ-4<br/>(II/performance)"]
  藝術_1_Ⅱ_5["藝術/1-Ⅱ-5<br/>(II/performance)"]
  藝術_1_Ⅱ_6["藝術/1-Ⅱ-6<br/>(II/performance)"]
  藝術_1_Ⅱ_7["藝術/1-Ⅱ-7<br/>(II/performance)"]
  藝術_1_Ⅱ_8["藝術/1-Ⅱ-8<br/>(II/performance)"]
  藝術_2_Ⅱ_1["藝術/2-Ⅱ-1<br/>(II/performance)"]
  藝術_2_Ⅱ_2["藝術/2-Ⅱ-2<br/>(II/performance)"]
  藝術_2_Ⅱ_3["藝術/2-Ⅱ-3<br/>(II/performance)"]
  藝術_2_Ⅱ_4["藝術/2-Ⅱ-4<br/>(II/performance)"]
  藝術_2_Ⅱ_5["藝術/2-Ⅱ-5<br/>(II/performance)"]
  藝術_2_Ⅱ_6["藝術/2-Ⅱ-6<br/>(II/performance)"]
  藝術_2_Ⅱ_7["藝術/2-Ⅱ-7<br/>(II/performance)"]
  藝術_3_Ⅱ_1["藝術/3-Ⅱ-1<br/>(II/performance)"]
  藝術_3_Ⅱ_2["藝術/3-Ⅱ-2<br/>(II/performance)"]
  藝術_3_Ⅱ_3["藝術/3-Ⅱ-3<br/>(II/performance)"]
  藝術_3_Ⅱ_4["藝術/3-Ⅱ-4<br/>(II/performance)"]
  藝術_3_Ⅱ_5["藝術/3-Ⅱ-5<br/>(II/performance)"]
  藝術_1_Ⅲ_1["藝術/1-Ⅲ-1<br/>(III/performance)"]
  藝術_1_Ⅲ_2["藝術/1-Ⅲ-2<br/>(III/performance)"]
  藝術_1_Ⅲ_3["藝術/1-Ⅲ-3<br/>(III/performance)"]
  藝術_1_Ⅲ_4["藝術/1-Ⅲ-4<br/>(III/performance)"]
  藝術_1_Ⅲ_5["藝術/1-Ⅲ-5<br/>(III/performance)"]
  藝術_1_Ⅲ_6["藝術/1-Ⅲ-6<br/>(III/performance)"]
  藝術_1_Ⅲ_7["藝術/1-Ⅲ-7<br/>(III/performance)"]
  藝術_1_Ⅲ_8["藝術/1-Ⅲ-8<br/>(III/performance)"]
  藝術_2_Ⅲ_1["藝術/2-Ⅲ-1<br/>(III/performance)"]
  藝術_2_Ⅲ_2["藝術/2-Ⅲ-2<br/>(III/performance)"]
  藝術_2_Ⅲ_3["藝術/2-Ⅲ-3<br/>(III/performance)"]
  藝術_2_Ⅲ_4["藝術/2-Ⅲ-4<br/>(III/performance)"]
  藝術_2_Ⅲ_5["藝術/2-Ⅲ-5<br/>(III/performance)"]
  藝術_2_Ⅲ_6["藝術/2-Ⅲ-6<br/>(III/performance)"]
  藝術_2_Ⅲ_7["藝術/2-Ⅲ-7<br/>(III/performance)"]
  藝術_3_Ⅲ_1["藝術/3-Ⅲ-1<br/>(III/performance)"]
  藝術_3_Ⅲ_2["藝術/3-Ⅲ-2<br/>(III/performance)"]
  藝術_3_Ⅲ_3["藝術/3-Ⅲ-3<br/>(III/performance)"]
  藝術_3_Ⅲ_4["藝術/3-Ⅲ-4<br/>(III/performance)"]
  藝術_3_Ⅲ_5["藝術/3-Ⅲ-5<br/>(III/performance)"]
  藝術_1_Ⅳ_1["藝術/1-Ⅳ-1<br/>(IV/performance)"]
  藝術_1_Ⅳ_2["藝術/1-Ⅳ-2<br/>(IV/performance)"]
  藝術_2_Ⅳ_1["藝術/2-Ⅳ-1<br/>(IV/performance)"]
  藝術_2_Ⅳ_2["藝術/2-Ⅳ-2<br/>(IV/performance)"]
  藝術_3_Ⅳ_1["藝術/3-Ⅳ-1<br/>(IV/performance)"]
  藝術_3_Ⅳ_2["藝術/3-Ⅳ-2<br/>(IV/performance)"]
  藝術_1_Ⅳ_3["藝術/1-Ⅳ-3<br/>(IV/performance)"]
  藝術_1_Ⅳ_4["藝術/1-Ⅳ-4<br/>(IV/performance)"]
  藝術_2_Ⅳ_3["藝術/2-Ⅳ-3<br/>(IV/performance)"]
  藝術_3_Ⅳ_3["藝術/3-Ⅳ-3<br/>(IV/performance)"]
  藝術_3_Ⅳ_4["藝術/3-Ⅳ-4<br/>(IV/performance)"]
  藝術_1_V_1["藝術/1-V-1<br/>(V/performance)"]
  藝術_1_V_2["藝術/1-V-2<br/>(V/performance)"]
  藝術_1_V_3["藝術/1-V-3<br/>(V/performance)"]
  藝術_2_V_1["藝術/2-V-1<br/>(V/performance)"]
  藝術_2_V_2["藝術/2-V-2<br/>(V/performance)"]
  藝術_3_V_1["藝術/3-V-1<br/>(V/performance)"]
  藝術_3_V_2["藝術/3-V-2<br/>(V/performance)"]
  藝術_1_V_4["藝術/1-V-4<br/>(V/performance)"]
  藝術_1_V_5["藝術/1-V-5<br/>(V/performance)"]
  藝術_2_V_3["藝術/2-V-3<br/>(V/performance)"]
  藝術_3_V_3["藝術/3-V-3<br/>(V/performance)"]
  藝術_3_V_4["藝術/3-V-4<br/>(V/performance)"]
  藝術_E_Ⅱ_1 -->|prerequisite| 藝術_E_Ⅲ_1
  藝術_E_Ⅲ_1 -->|prerequisite| 藝術_E_Ⅳ_1
  藝術_E_Ⅳ_1 -->|prerequisite| 藝術_E_V_1
  藝術_E_Ⅱ_2 -->|prerequisite| 藝術_E_Ⅲ_2
  藝術_E_Ⅲ_2 -->|prerequisite| 藝術_E_Ⅳ_2
  藝術_E_Ⅳ_2 -->|prerequisite| 藝術_E_V_2
  藝術_E_Ⅱ_3 -->|prerequisite| 藝術_E_Ⅲ_3
  藝術_E_Ⅲ_3 -->|prerequisite| 藝術_E_Ⅳ_3
  藝術_E_Ⅳ_3 -->|prerequisite| 藝術_E_V_3
  藝術_E_Ⅱ_4 -->|prerequisite| 藝術_E_Ⅲ_4
  藝術_E_Ⅲ_4 -->|prerequisite| 藝術_E_Ⅳ_4
  藝術_E_Ⅳ_4 -->|prerequisite| 藝術_E_V_4
  藝術_E_Ⅱ_5 -->|prerequisite| 藝術_E_Ⅲ_5
  藝術_E_Ⅲ_5 -->|prerequisite| 藝術_E_Ⅳ_5
  藝術_E_Ⅳ_5 -->|prerequisite| 藝術_E_V_5
  藝術_A_Ⅱ_1 -->|prerequisite| 藝術_A_Ⅲ_1
  藝術_A_Ⅲ_1 -->|prerequisite| 藝術_A_Ⅳ_1
  藝術_A_Ⅳ_1 -->|prerequisite| 藝術_A_V_1
  藝術_A_Ⅱ_2 -->|prerequisite| 藝術_A_Ⅲ_2
  藝術_A_Ⅲ_2 -->|prerequisite| 藝術_A_Ⅳ_2
  藝術_A_Ⅳ_2 -->|prerequisite| 藝術_A_V_2
  藝術_A_Ⅱ_3 -->|prerequisite| 藝術_A_Ⅲ_3
  藝術_A_Ⅲ_3 -->|prerequisite| 藝術_A_Ⅳ_3
  藝術_A_Ⅳ_3 -->|prerequisite| 藝術_A_V_3
  藝術_P_Ⅱ_1 -->|prerequisite| 藝術_P_Ⅲ_1
  藝術_P_Ⅲ_1 -->|prerequisite| 藝術_P_Ⅳ_1
  藝術_P_Ⅳ_1 -->|prerequisite| 藝術_P_V_1
  藝術_P_Ⅱ_2 -->|prerequisite| 藝術_P_Ⅲ_2
  藝術_P_Ⅲ_2 -->|prerequisite| 藝術_P_Ⅳ_2
  藝術_P_Ⅳ_2 -->|prerequisite| 藝術_P_V_2
  藝術_P_Ⅱ_3 -->|prerequisite| 藝術_P_Ⅲ_3
  藝術_P_Ⅲ_3 -->|prerequisite| 藝術_P_Ⅳ_3
  藝術_P_Ⅳ_3 -->|prerequisite| 藝術_P_V_3
  藝術_P_Ⅱ_4 -->|prerequisite| 藝術_P_Ⅲ_4
  藝術_P_Ⅲ_4 -->|prerequisite| 藝術_P_Ⅳ_4
  藝術_P_Ⅳ_4 -->|prerequisite| 藝術_P_V_4
  藝術_1_Ⅱ_1 -->|prerequisite| 藝術_1_Ⅲ_1
  藝術_1_Ⅲ_1 -->|prerequisite| 藝術_1_Ⅳ_1
  藝術_1_Ⅳ_1 -->|prerequisite| 藝術_1_V_1
  藝術_1_Ⅱ_2 -->|prerequisite| 藝術_1_Ⅲ_2
  藝術_1_Ⅲ_2 -->|prerequisite| 藝術_1_Ⅳ_2
  藝術_1_Ⅳ_2 -->|prerequisite| 藝術_1_V_2
  藝術_1_Ⅱ_3 -->|prerequisite| 藝術_1_Ⅲ_3
  藝術_1_Ⅲ_3 -->|prerequisite| 藝術_1_Ⅳ_3
  藝術_1_Ⅳ_3 -->|prerequisite| 藝術_1_V_3
  藝術_1_Ⅱ_4 -->|prerequisite| 藝術_1_Ⅲ_4
  藝術_1_Ⅲ_4 -->|prerequisite| 藝術_1_Ⅳ_4
  藝術_1_Ⅳ_4 -->|prerequisite| 藝術_1_V_4
  藝術_1_Ⅱ_5 -->|prerequisite| 藝術_1_Ⅲ_5
  藝術_1_Ⅲ_5 -->|prerequisite| 藝術_1_V_5
  藝術_1_Ⅱ_6 -->|prerequisite| 藝術_1_Ⅲ_6
  藝術_1_Ⅱ_7 -->|prerequisite| 藝術_1_Ⅲ_7
  藝術_1_Ⅱ_8 -->|prerequisite| 藝術_1_Ⅲ_8
  藝術_2_Ⅱ_1 -->|prerequisite| 藝術_2_Ⅲ_1
  藝術_2_Ⅲ_1 -->|prerequisite| 藝術_2_Ⅳ_1
  藝術_2_Ⅳ_1 -->|prerequisite| 藝術_2_V_1
  藝術_2_Ⅱ_2 -->|prerequisite| 藝術_2_Ⅲ_2
  藝術_2_Ⅲ_2 -->|prerequisite| 藝術_2_Ⅳ_2
  藝術_2_Ⅳ_2 -->|prerequisite| 藝術_2_V_2
  藝術_2_Ⅱ_3 -->|prerequisite| 藝術_2_Ⅲ_3
  藝術_2_Ⅲ_3 -->|prerequisite| 藝術_2_Ⅳ_3
  藝術_2_Ⅳ_3 -->|prerequisite| 藝術_2_V_3
  藝術_2_Ⅱ_4 -->|prerequisite| 藝術_2_Ⅲ_4
  藝術_2_Ⅱ_5 -->|prerequisite| 藝術_2_Ⅲ_5
  藝術_2_Ⅱ_6 -->|prerequisite| 藝術_2_Ⅲ_6
  藝術_2_Ⅱ_7 -->|prerequisite| 藝術_2_Ⅲ_7
  藝術_3_Ⅱ_1 -->|prerequisite| 藝術_3_Ⅲ_1
  藝術_3_Ⅲ_1 -->|prerequisite| 藝術_3_Ⅳ_1
  藝術_3_Ⅳ_1 -->|prerequisite| 藝術_3_V_1
  藝術_3_Ⅱ_2 -->|prerequisite| 藝術_3_Ⅲ_2
  藝術_3_Ⅲ_2 -->|prerequisite| 藝術_3_Ⅳ_2
  藝術_3_Ⅳ_2 -->|prerequisite| 藝術_3_V_2
  藝術_3_Ⅱ_3 -->|prerequisite| 藝術_3_Ⅲ_3
  藝術_3_Ⅲ_3 -->|prerequisite| 藝術_3_Ⅳ_3
  藝術_3_Ⅳ_3 -->|prerequisite| 藝術_3_V_3
  藝術_3_Ⅱ_4 -->|prerequisite| 藝術_3_Ⅲ_4
  藝術_3_Ⅲ_4 -->|prerequisite| 藝術_3_Ⅳ_4
  藝術_3_Ⅳ_4 -->|prerequisite| 藝術_3_V_4
  藝術_3_Ⅱ_5 -->|prerequisite| 藝術_3_Ⅲ_5
