graph LR
  科技_A_IV_1["科技/A-IV-1<br/>(IV/content)"]
  科技_A_IV_2["科技/A-IV-2<br/>(IV/content)"]
  科技_A_IV_3["科技/A-IV-3<br/>(IV/content)"]
  科技_P_IV_1["科技/P-IV-1<br/>(IV/content)"]
  科技_P_IV_2["科技/P-IV-2<br/>(IV/content)"]
  科技_P_IV_3["科技/P-IV-3<br/>(IV/content)"]
  科技_P_IV_4["科技/P-IV-4<br/>(IV/content)"]
  科技_P_IV_5["科技/P-IV-5<br/>(IV/content)"]
  科技_S_IV_1["科技/S-IV-1<br/>(IV/content)"]
  科技_S_IV_2["科技/S-IV-2<br/>(IV/content)"]
  科技_S_IV_3["科技/S-IV-3<br/>(IV/content)"]
  科技_S_IV_4["科技/S-IV-4<br/>(IV/content)"]
  科技_D_IV_1["科技/D-IV-1<br/>(IV/content)"]
  科技_D_IV_2["科技/D-IV-2<br/>(IV/content)"]
  科技_D_IV_3["科技/D-IV-3<br/>(IV/content)"]
  科技_T_IV_1["科技/T-IV-1<br/>(IV/content)"]
  科技_T_IV_2["科技/T-IV-2<br/>(IV/content)"]
  科技_H_IV_1["科技/H-IV-1<br/>(IV/content)"]
  科技_H_IV_2["科技/H-IV-2<br/>(IV/content)"]
  科技_H_IV_3["科技/H-IV-3<br/>(IV/content)"]
  科技_H_IV_4["科技/H-IV-4<br/>(IV/content)"]
  科技_H_IV_5["科技/H-IV-5<br/>(IV/content)"]
  科技_H_IV_6["科技/H-IV-6<br/>(IV/content)"]
  科技_H_IV_7["科技/H-IV-7<br/>(IV/content)"]
  科技_A_V_1["科技/A-V-1<br/>(V/content)"]
  科技_A_V_2["科技/A-V-2<br/>(V/content)"]
  科技_A_V_3["科技/A-V-3<br/>(V/content)"]
  科技_P_V_1["科技/P-V-1<br/>(V/content)"]
  科技_P_V_2["科技/P-V-2<br/>(V/content)"]
  科技_P_V_3["科技/P-V-3<br/>(V/content)"]
  科技_S_V_1["科技/S-V-1<br/>(V/content)"]
  科技_S_V_2["科技/S-V-2<br/>(V/content)"]
  科技_D_V_1["科技/D-V-1<br/>(V/content)"]
  科技_D_V_2["科技/D-V-2<br/>(V/content)"]
  科技_T_V_1["科技/T-V-1<br/>(V/content)"]
  科技_H_V_1["科技/H-V-1<br/>(V/content)"]
  科技_H_V_2["科技/H-V-2<br/>(V/content)"]
  科技_H_V_3["科技/H-V-3<br/>(V/content)"]
  科技_N_IV_1["科技/N-IV-1<br/>(IV/content)"]
  科技_N_IV_2["科技/N-IV-2<br/>(IV/content)"]
  科技_N_IV_3["科技/N-IV-3<br/>(IV/content)"]
  科技_P_IV_6["科技/P-IV-6<br/>(IV/content)"]
  科技_P_IV_7["科技/P-IV-7<br/>(IV/content)"]
  科技_A_IV_4["科技/A-IV-4<br/>(IV/content)"]
  科技_A_IV_5["科技/A-IV-5<br/>(IV/content)"]
  科技_A_IV_6["科技/A-IV-6<br/>(IV/content)"]
  科技_N_V_1["科技/N-V-1<br/>(V/content)"]
  科技_N_V_2["科技/N-V-2<br/>(V/content)"]
  科技_L_V_1["科技/L-V-1<br/>(V/content)"]
  科技_L_V_2["科技/L-V-2<br/>(V/content)"]
  科技_Da_V_1["科技/Da-V-1<br/>(V/content)"]
  科技_Da_V_2["科技/Da-V-2<br/>(V/content)"]
  科技_A_V_4["科技/A-V-4<br/>(V/content)"]
  科技_A_V_5["科技/A-V-5<br/>(V/content)"]
  科技_A_V_6["科技/A-V-6<br/>(V/content)"]
  科技_I_V_1["科技/I-V-1<br/>(V/content)"]
  科技_I_V_2["科技/I-V-2<br/>(V/content)"]
  科技_A_V_7["科技/A-V-7<br/>(V/content)"]
  科技_Rd_V_1["科技/Rd-V-1<br/>(V/content)"]
  科技_Rc_V_1["科技/Rc-V-1<br/>(V/content)"]
  科技_Rc_V_2["科技/Rc-V-2<br/>(V/content)"]
  科技_Rc_V_3["科技/Rc-V-3<br/>(V/content)"]
  科技_Rp_V_1["科技/Rp-V-1<br/>(V/content)"]
  科技_Tt_V_1["科技/Tt-V-1<br/>(V/content)"]
  科技_Tp_V_1["科技/Tp-V-1<br/>(V/content)"]
  科技_Tp_V_2["科技/Tp-V-2<br/>(V/content)"]
  科技_t_IV_1["科技/t-IV-1<br/>(IV/performance)"]
  科技_t_IV_2["科技/t-IV-2<br/>(IV/performance)"]
  科技_t_IV_3["科技/t-IV-3<br/>(IV/performance)"]
  科技_t_IV_4["科技/t-IV-4<br/>(IV/performance)"]
  科技_t_V_1["科技/t-V-1<br/>(V/performance)"]
  科技_t_V_2["科技/t-V-2<br/>(V/performance)"]
  科技_t_V_3["科技/t-V-3<br/>(V/performance)"]
  科技_c_IV_1["科技/c-IV-1<br/>(IV/performance)"]
  科技_c_IV_2["科技/c-IV-2<br/>(IV/performance)"]
  科技_c_IV_3["科技/c-IV-3<br/>(IV/performance)"]
  科技_c_V_1["科技/c-V-1<br/>(V/performance)"]
  科技_c_V_2["科技/c-V-2<br/>(V/performance)"]
  科技_c_V_3["科技/c-V-3<br/>(V/performance)"]
  科技_p_IV_1["科技/p-IV-1<br/>(IV/performance)"]
  科技_p_IV_2["科技/p-IV-2<br/>(IV/performance)"]
  科技_p_IV_3["科技/p-IV-3<br/>(IV/performance)"]
  科技_p_V_1["科技/p-V-1<br/>(V/performance)"]
  科技_a_IV_1["科技/a-IV-1<br/>(IV/performance)"]
  科技_a_IV_2["科技/a-IV-2<br/>(IV/performance)"]
  科技_a_IV_3["科技/a-IV-3<br/>(IV/performance)"]
  科技_a_V_1["科技/a-V-1<br/>(V/performance)"]
  科技_a_V_2["科技/a-V-2<br/>(V/performance)"]
  科技_a_V_3["科技/a-V-3<br/>(V/performance)"]
  科技_a_V_4["科技/a-V-4<br/>(V/performance)"]
  科技_a_V_5["科技/a-V-5<br/>(V/performance)"]
  科技_a_V_6["科技/a-V-6<br/>(V/performance)"]
  科技_r_V_1["科技/r-V-1<br/>(V/performance)"]
  科技_r_V_2["科技/r-V-2<br/>(V/performance)"]
  科技_r_V_3["科技/r-V-3<br/>(V/performance)"]
  科技_r_V_4["科技/r-V-4<br/>(V/performance)"]
  科技_m_V_1["科技/m-V-1<br/>(V/performance)"]
  科技_m_V_2["科技/m-V-2<br/>(V/performance)"]
  科技_k_IV_1["科技/k-IV-1<br/>(IV/performance)"]
  科技_k_IV_2["科技/k-IV-2<br/>(IV/performance)"]
  科技_k_IV_3["科技/k-IV-3<br/>(IV/performance)"]
  科技_k_IV_4["科技/k-IV-4<br/>(IV/performance)"]
  科技_k_V_1["科技/k-V-1<br/>(V/performance)"]
  科技_k_V_2["科技/k-V-2<br/>(V/performance)"]
  科技_k_V_3["科技/k-V-3<br/>(V/performance)"]
  科技_a_IV_4["科技/a-IV-4<br/>(IV/performance)"]
  科技_s_IV_1["科技/s-IV-1<br/>(IV/performance)"]
  科技_s_IV_2["科技/s-IV-2<br/>(IV/performance)"]
  科技_s_IV_3["科技/s-IV-3<br/>(IV/performance)"]
  科技_s_V_1["科技/s-V-1<br/>(V/performance)"]
  科技_s_V_2["科技/s-V-2<br/>(V/performance)"]
  科技_s_V_3["科技/s-V-3<br/>(V/performance)"]
  科技_A_IV_1 -->|prerequisite| 科技_A_V_1
  科技_A_IV_2 -->|prerequisite| 科技_A_V_2
  科技_A_IV_3 -->|prerequisite| 科技_A_V_3
  科技_P_IV_1 -->|prerequisite| 科技_P_V_1
  科技_P_IV_2 -->|prerequisite| 科技_P_V_2
  科技_P_IV_3 -->|prerequisite| 科技_P_V_3
  科技_S_IV_1 -->|prerequisite| 科技_S_V_1
  科技_S_IV_2 -->|prerequisite| 科技_S_V_2
  科技_D_IV_1 -->|prerequisite| 科技_D_V_1
  科技_D_IV_2 -->|prerequisite| 科技_D_V_2
  科技_T_IV_1 -->|prerequisite| 科技_T_V_1
  科技_H_IV_1 -->|prerequisite| 科技_H_V_1
  科技_H_IV_2 -->|prerequisite| 科技_H_V_2
  科技_H_IV_3 -->|prerequisite| 科技_H_V_3
  科技_N_IV_1 -->|prerequisite| 科技_N_V_1
  科技_N_IV_2 -->|prerequisite| 科技_N_V_2
  科技_A_IV_4 -->|prerequisite| 科技_A_V_4
  科技_A_IV_5 -->|prerequisite| 科技_A_V_5
  科技_A_IV_6 -->|prerequisite| 科技_A_V_6
  科技_t_IV_1 -->|prerequisite| 科技_t_V_1
  科技_t_IV_2 -->|prerequisite| 科技_t_V_2
  科技_t_IV_3 -->|prerequisite| 科技_t_V_3
  科技_c_IV_1 -->|prerequisite| 科技_c_V_1
  科技_c_IV_2 -->|prerequisite| 科技_c_V_2
  科技_c_IV_3 -->|prerequisite| 科技_c_V_3
  科技_p_IV_1 -->|prerequisite| 科技_p_V_1
  科技_a_IV_1 -->|prerequisite| 科技_a_V_1
  科技_a_IV_2 -->|prerequisite| 科技_a_V_2
  科技_a_IV_3 -->|prerequisite| 科技_a_V_3
  科技_a_IV_4 -->|prerequisite| 科技_a_V_4
  科技_k_IV_1 -->|prerequisite| 科技_k_V_1
  科技_k_IV_2 -->|prerequisite| 科技_k_V_2
  科技_k_IV_3 -->|prerequisite| 科技_k_V_3
  科技_s_IV_1 -->|prerequisite| 科技_s_V_1
  科技_s_IV_2 -->|prerequisite| 科技_s_V_2
  科技_s_IV_3 -->|prerequisite| 科技_s_V_3
