graph LR
  綜合活動_Aa_II_1["綜合活動/Aa-II-1<br/>(II/content)"]
  綜合活動_Aa_IV_1["綜合活動/Aa-IV-1<br/>(IV/content)"]
  綜合活動_Aa_V_1["綜合活動/Aa-V-1<br/>(V/content)"]
  綜合活動_Aa_II_2["綜合活動/Aa-II-2<br/>(II/content)"]
  綜合活動_Aa_II_3["綜合活動/Aa-II-3<br/>(II/content)"]
  綜合活動_Aa_III_1["綜合活動/Aa-III-1<br/>(III/content)"]
  綜合活動_Aa_III_2["綜合活動/Aa-III-2<br/>(III/content)"]
  綜合活動_Ab_II_1["綜合活動/Ab-II-1<br/>(II/content)"]
  綜合活動_Ab_II_2["綜合活動/Ab-II-2<br/>(II/content)"]
  綜合活動_Ab_III_1["綜合活動/Ab-III-1<br/>(III/content)"]
  綜合活動_Ab_III_2["綜合活動/Ab-III-2<br/>(III/content)"]
  綜合活動_Ac_II_1["綜合活動/Ac-II-1<br/>(II/content)"]
  綜合活動_Ac_II_2["綜合活動/Ac-II-2<br/>(II/content)"]
  綜合活動_Ac_II_3["綜合活動/Ac-II-3<br/>(II/content)"]
  綜合活動_Ac_III_1["綜合活動/Ac-III-1<br/>(III/content)"]
  綜合活動_Ac_III_2["綜合活動/Ac-III-2<br/>(III/content)"]
  綜合活動_Ac_III_3["綜合活動/Ac-III-3<br/>(III/content)"]
  綜合活動_Ad_II_1["綜合活動/Ad-II-1<br/>(II/content)"]
  綜合活動_Ad_II_2["綜合活動/Ad-II-2<br/>(II/content)"]
  綜合活動_Ad_III_1["綜合活動/Ad-III-1<br/>(III/content)"]
  綜合活動_Ad_III_2["綜合活動/Ad-III-2<br/>(III/content)"]
  綜合活動_Ad_III_3["綜合活動/Ad-III-3<br/>(III/content)"]
  綜合活動_Ad_III_4["綜合活動/Ad-III-4<br/>(III/content)"]
  綜合活動_Ba_II_1["綜合活動/Ba-II-1<br/>(II/content)"]
  綜合活動_Ba_II_2["綜合活動/Ba-II-2<br/>(II/content)"]
  綜合活動_Ba_II_3["綜合活動/Ba-II-3<br/>(II/content)"]
  綜合活動_Ba_III_1["綜合活動/Ba-III-1<br/>(III/content)"]
  綜合活動_Ba_III_2["綜合活動/Ba-III-2<br/>(III/content)"]
  綜合活動_Ba_III_3["綜合活動/Ba-III-3<br/>(III/content)"]
  綜合活動_Bb_II_1["綜合活動/Bb-II-1<br/>(II/content)"]
  綜合活動_Bb_II_2["綜合活動/Bb-II-2<br/>(II/content)"]
  綜合活動_Bb_II_3["綜合活動/Bb-II-3<br/>(II/content)"]
  綜合活動_Bb_III_1["綜合活動/Bb-III-1<br/>(III/content)"]
  綜合活動_Bb_III_2["綜合活動/Bb-III-2<br/>(III/content)"]
  綜合活動_Bb_III_3["綜合活動/Bb-III-3<br/>(III/content)"]
  綜合活動_Bc_II_1["綜合活動/Bc-II-1<br/>(II/content)"]
  綜合活動_Bc_II_2["綜合活動/Bc-II-2<br/>(II/content)"]
  綜合活動_Bc_II_3["綜合活動/Bc-II-3<br/>(II/content)"]
  綜合活動_Bc_III_1["綜合活動/Bc-III-1<br/>(III/content)"]
  綜合活動_Bc_III_2["綜合活動/Bc-III-2<br/>(III/content)"]
  綜合活動_Bc_III_3["綜合活動/Bc-III-3<br/>(III/content)"]
  綜合活動_Bd_II_1["綜合活動/Bd-II-1<br/>(II/content)"]
  綜合活動_Bd_II_2["綜合活動/Bd-II-2<br/>(II/content)"]
  綜合活動_Bd_II_3["綜合活動/Bd-II-3<br/>(II/content)"]
  綜合活動_Bd_III_1["綜合活動/Bd-III-1<br/>(III/content)"]
  綜合活動_Bd_III_2["綜合活動/Bd-III-2<br/>(III/content)"]
  綜合活動_Ca_II_1["綜合活動/Ca-II-1<br/>(II/content)"]
  綜合活動_Ca_II_2["綜合活動/Ca-II-2<br/>(II/content)"]
  綜合活動_Ca_II_3["綜合活動/Ca-II-3<br/>(II/content)"]
  綜合活動_Ca_III_1["綜合活動/Ca-III-1<br/>(III/content)"]
  綜合活動_Ca_III_2["綜合活動/Ca-III-2<br/>(III/content)"]
  綜合活動_Ca_III_3["綜合活動/Ca-III-3<br/>(III/content)"]
  綜合活動_Cb_II_1["綜合活動/Cb-II-1<br/>(II/content)"]
  綜合活動_Cb_II_2["綜合活動/Cb-II-2<br/>(II/content)"]
  綜合活動_Cb_III_1["綜合活動/Cb-III-1<br/>(III/content)"]
  綜合活動_Cb_III_2["綜合活動/Cb-III-2<br/>(III/content)"]
  綜合活動_Cb_III_3["綜合活動/Cb-III-3<br/>(III/content)"]
  綜合活動_Cc_II_1["綜合活動/Cc-II-1<br/>(II/content)"]
  綜合活動_Cc_II_2["綜合活動/Cc-II-2<br/>(II/content)"]
  綜合活動_Cc_II_3["綜合活動/Cc-II-3<br/>(II/content)"]
  綜合活動_Cc_III_1["綜合活動/Cc-III-1<br/>(III/content)"]
  綜合活動_Cc_III_2["綜合活動/Cc-III-2<br/>(III/content)"]
  綜合活動_Cc_III_3["綜合活動/Cc-III-3<br/>(III/content)"]
  綜合活動_Cc_III_4["綜合活動/Cc-III-4<br/>(III/content)"]
  綜合活動_Cd_II_1["綜合活動/Cd-II-1<br/>(II/content)"]
  綜合活動_Cd_II_2["綜合活動/Cd-II-2<br/>(II/content)"]
  綜合活動_Cd_III_1["綜合活動/Cd-III-1<br/>(III/content)"]
  綜合活動_Cd_III_2["綜合活動/Cd-III-2<br/>(III/content)"]
  綜合活動_Cd_III_3["綜合活動/Cd-III-3<br/>(III/content)"]
  綜合活動_Cd_III_4["綜合活動/Cd-III-4<br/>(III/content)"]
  綜合活動_Db_IV_1["綜合活動/Db-IV-1<br/>(IV/content)"]
  綜合活動_Ab_IV_1["綜合活動/Ab-IV-1<br/>(IV/content)"]
  綜合活動_Ab_IV_2["綜合活動/Ab-IV-2<br/>(IV/content)"]
  綜合活動_Cc_IV_2["綜合活動/Cc-IV-2<br/>(IV/content)"]
  綜合活動_Aa_IV_2["綜合活動/Aa-IV-2<br/>(IV/content)"]
  綜合活動_Bc_IV_2["綜合活動/Bc-IV-2<br/>(IV/content)"]
  綜合活動_Dd_IV_1["綜合活動/Dd-IV-1<br/>(IV/content)"]
  綜合活動_Ca_IV_1["綜合活動/Ca-IV-1<br/>(IV/content)"]
  綜合活動_Ba_IV_1["綜合活動/Ba-IV-1<br/>(IV/content)"]
  綜合活動_Ba_IV_2["綜合活動/Ba-IV-2<br/>(IV/content)"]
  綜合活動_Bb_IV_1["綜合活動/Bb-IV-1<br/>(IV/content)"]
  綜合活動_Db_IV_2["綜合活動/Db-IV-2<br/>(IV/content)"]
  綜合活動_Cc_IV_1["綜合活動/Cc-IV-1<br/>(IV/content)"]
  綜合活動_Dd_IV_2["綜合活動/Dd-IV-2<br/>(IV/content)"]
  綜合活動_Dd_IV_3["綜合活動/Dd-IV-3<br/>(IV/content)"]
  綜合活動_Ca_IV_2["綜合活動/Ca-IV-2<br/>(IV/content)"]
  綜合活動_Cb_IV_1["綜合活動/Cb-IV-1<br/>(IV/content)"]
  綜合活動_Bb_IV_3["綜合活動/Bb-IV-3<br/>(IV/content)"]
  綜合活動_Cb_IV_2["綜合活動/Cb-IV-2<br/>(IV/content)"]
  綜合活動_Da_IV_1["綜合活動/Da-IV-1<br/>(IV/content)"]
  綜合活動_Da_IV_2["綜合活動/Da-IV-2<br/>(IV/content)"]
  綜合活動_Ac_IV_1["綜合活動/Ac-IV-1<br/>(IV/content)"]
  綜合活動_Ac_IV_2["綜合活動/Ac-IV-2<br/>(IV/content)"]
  綜合活動_Dc_IV_1["綜合活動/Dc-IV-1<br/>(IV/content)"]
  綜合活動_Aa_IV_3["綜合活動/Aa-IV-3<br/>(IV/content)"]
  綜合活動_Cb_IV_3["綜合活動/Cb-IV-3<br/>(IV/content)"]
  綜合活動_家Db_IV_3["綜合活動/家Db-IV-3<br/>(IV/content)"]
  綜合活動_輔Dd_IV_2["綜合活動/輔Dd-IV-2<br/>(IV/content)"]
  綜合活動_家Da_IV_1["綜合活動/家Da-IV-1<br/>(IV/content)"]
  綜合活動_家Da_IV_2["綜合活動/家Da-IV-2<br/>(IV/content)"]
  綜合活動_輔Dc_IV_1["綜合活動/輔Dc-IV-1<br/>(IV/content)"]
  綜合活動_Dc_IV_2["綜合活動/Dc-IV-2<br/>(IV/content)"]
  綜合活動_童Aa_IV_2["綜合活動/童Aa-IV-2<br/>(IV/content)"]
  綜合活動_童Bb_IV_2["綜合活動/童Bb-IV-2<br/>(IV/content)"]
  綜合活動_童Cb_IV_3["綜合活動/童Cb-IV-3<br/>(IV/content)"]
  綜合活動_輔Dc_IV_2["綜合活動/輔Dc-IV-2<br/>(IV/content)"]
  綜合活動_Bc_IV_1["綜合活動/Bc-IV-1<br/>(IV/content)"]
  綜合活動_Bb_IV_2["綜合活動/Bb-IV-2<br/>(IV/content)"]
  綜合活動_家Ab_IV_2["綜合活動/家Ab-IV-2<br/>(IV/content)"]
  綜合活動_家Cc_IV_1["綜合活動/家Cc-IV-1<br/>(IV/content)"]
  綜合活動_家Cc_IV_2["綜合活動/家Cc-IV-2<br/>(IV/content)"]
  綜合活動_家Dc_IV_1["綜合活動/家Dc-IV-1<br/>(IV/content)"]
  綜合活動_童Ca_IV_3["綜合活動/童Ca-IV-3<br/>(IV/content)"]
  綜合活動_輔Bc_IV_1["綜合活動/輔Bc-IV-1<br/>(IV/content)"]
  綜合活動_輔Da_IV_1["綜合活動/輔Da-IV-1<br/>(IV/content)"]
  綜合活動_Bb_IV_4["綜合活動/Bb-IV-4<br/>(IV/content)"]
  綜合活動_Ab_IV_3["綜合活動/Ab-IV-3<br/>(IV/content)"]
  綜合活動_Ca_IV_3["綜合活動/Ca-IV-3<br/>(IV/content)"]
  綜合活動_Db_IV_3["綜合活動/Db-IV-3<br/>(IV/content)"]
  綜合活動_Aa_V_2["綜合活動/Aa-V-2<br/>(V/content)"]
  綜合活動_Aa_V_3["綜合活動/Aa-V-3<br/>(V/content)"]
  綜合活動_Aa_V_4["綜合活動/Aa-V-4<br/>(V/content)"]
  綜合活動_Ab_V_1["綜合活動/Ab-V-1<br/>(V/content)"]
  綜合活動_Ba_V_1["綜合活動/Ba-V-1<br/>(V/content)"]
  綜合活動_Bb_V_1["綜合活動/Bb-V-1<br/>(V/content)"]
  綜合活動_Bb_V_2["綜合活動/Bb-V-2<br/>(V/content)"]
  綜合活動_Ca_V_1["綜合活動/Ca-V-1<br/>(V/content)"]
  綜合活動_Ca_V_2["綜合活動/Ca-V-2<br/>(V/content)"]
  綜合活動_Ca_V_3["綜合活動/Ca-V-3<br/>(V/content)"]
  綜合活動_Ca_V_4["綜合活動/Ca-V-4<br/>(V/content)"]
  綜合活動_Cb_V_1["綜合活動/Cb-V-1<br/>(V/content)"]
  綜合活動_Cb_V_2["綜合活動/Cb-V-2<br/>(V/content)"]
  綜合活動_Da_V_1["綜合活動/Da-V-1<br/>(V/content)"]
  綜合活動_Da_V_2["綜合活動/Da-V-2<br/>(V/content)"]
  綜合活動_Da_V_3["綜合活動/Da-V-3<br/>(V/content)"]
  綜合活動_Da_V_4["綜合活動/Da-V-4<br/>(V/content)"]
  綜合活動_Da_V_5["綜合活動/Da-V-5<br/>(V/content)"]
  綜合活動_Db_V_1["綜合活動/Db-V-1<br/>(V/content)"]
  綜合活動_Db_V_2["綜合活動/Db-V-2<br/>(V/content)"]
  綜合活動_Db_V_3["綜合活動/Db-V-3<br/>(V/content)"]
  綜合活動_Ea_V_1["綜合活動/Ea-V-1<br/>(V/content)"]
  綜合活動_Ea_V_2["綜合活動/Ea-V-2<br/>(V/content)"]
  綜合活動_Eb_V_1["綜合活動/Eb-V-1<br/>(V/content)"]
  綜合活動_Eb_V_2["綜合活動/Eb-V-2<br/>(V/content)"]
  綜合活動_Ab_V_2["綜合活動/Ab-V-2<br/>(V/content)"]
  綜合活動_Ac_V_1["綜合活動/Ac-V-1<br/>(V/content)"]
  綜合活動_Ac_V_2["綜合活動/Ac-V-2<br/>(V/content)"]
  綜合活動_Ac_V_3["綜合活動/Ac-V-3<br/>(V/content)"]
  綜合活動_Ac_V_4["綜合活動/Ac-V-4<br/>(V/content)"]
  綜合活動_Ba_V_2["綜合活動/Ba-V-2<br/>(V/content)"]
  綜合活動_Ba_V_3["綜合活動/Ba-V-3<br/>(V/content)"]
  綜合活動_Ba_V_4["綜合活動/Ba-V-4<br/>(V/content)"]
  綜合活動_Ba_V_5["綜合活動/Ba-V-5<br/>(V/content)"]
  綜合活動_涯Bb_V_1["綜合活動/涯Bb-V-1<br/>(V/content)"]
  綜合活動_涯Bb_V_2["綜合活動/涯Bb-V-2<br/>(V/content)"]
  綜合活動_Cc_V_1["綜合活動/Cc-V-1<br/>(V/content)"]
  綜合活動_Dc_V_1["綜合活動/Dc-V-1<br/>(V/content)"]
  綜合活動_Dc_V_2["綜合活動/Dc-V-2<br/>(V/content)"]
  綜合活動_Aa_V_5["綜合活動/Aa-V-5<br/>(V/content)"]
  綜合活動_Aa_V_6["綜合活動/Aa-V-6<br/>(V/content)"]
  綜合活動_Aa_V_7["綜合活動/Aa-V-7<br/>(V/content)"]
  綜合活動_Ab_V_3["綜合活動/Ab-V-3<br/>(V/content)"]
  綜合活動_Ab_V_4["綜合活動/Ab-V-4<br/>(V/content)"]
  綜合活動_Ca_V_5["綜合活動/Ca-V-5<br/>(V/content)"]
  綜合活動_Ca_V_6["綜合活動/Ca-V-6<br/>(V/content)"]
  綜合活動_Ca_V_7["綜合活動/Ca-V-7<br/>(V/content)"]
  綜合活動_Cb_V_3["綜合活動/Cb-V-3<br/>(V/content)"]
  綜合活動_Cb_V_4["綜合活動/Cb-V-4<br/>(V/content)"]
  綜合活動_Da_V_6["綜合活動/Da-V-6<br/>(V/content)"]
  綜合活動_Da_V_7["綜合活動/Da-V-7<br/>(V/content)"]
  綜合活動_未Bb_V_1["綜合活動/未Bb-V-1<br/>(V/content)"]
  綜合活動_未Bb_V_2["綜合活動/未Bb-V-2<br/>(V/content)"]
  綜合活動_未Bb_V_3["綜合活動/未Bb-V-3<br/>(V/content)"]
  綜合活動_未Bb_V_4["綜合活動/未Bb-V-4<br/>(V/content)"]
  綜合活動_未Bb_V_5["綜合活動/未Bb-V-5<br/>(V/content)"]
  綜合活動_Cc_V_2["綜合活動/Cc-V-2<br/>(V/content)"]
  綜合活動_1a_II_1["綜合活動/1a-II-1<br/>(II/performance)"]
  綜合活動_1a_IV_1["綜合活動/1a-IV-1<br/>(IV/performance)"]
  綜合活動_1a_V_1["綜合活動/1a-V-1<br/>(V/performance)"]
  綜合活動_1a_III_1["綜合活動/1a-III-1<br/>(III/performance)"]
  綜合活動_1b_II_1["綜合活動/1b-II-1<br/>(II/performance)"]
  綜合活動_1b_III_1["綜合活動/1b-III-1<br/>(III/performance)"]
  綜合活動_1c_II_1["綜合活動/1c-II-1<br/>(II/performance)"]
  綜合活動_1c_III_1["綜合活動/1c-III-1<br/>(III/performance)"]
  綜合活動_1d_II_1["綜合活動/1d-II-1<br/>(II/performance)"]
  綜合活動_1d_III_1["綜合活動/1d-III-1<br/>(III/performance)"]
  綜合活動_2a_II_1["綜合活動/2a-II-1<br/>(II/performance)"]
  綜合活動_2a_III_1["綜合活動/2a-III-1<br/>(III/performance)"]
  綜合活動_2b_II_1["綜合活動/2b-II-1<br/>(II/performance)"]
  綜合活動_2b_II_2["綜合活動/2b-II-2<br/>(II/performance)"]
  綜合活動_2b_III_1["綜合活動/2b-III-1<br/>(III/performance)"]
  綜合活動_2c_II_1["綜合活動/2c-II-1<br/>(II/performance)"]
  綜合活動_2c_III_1["綜合活動/2c-III-1<br/>(III/performance)"]
  綜合活動_2d_II_1["綜合活動/2d-II-1<br/>(II/performance)"]
  綜合活動_2d_II_2["綜合活動/2d-II-2<br/>(II/performance)"]
  綜合活動_2d_III_1["綜合活動/2d-III-1<br/>(III/performance)"]
  綜合活動_2d_III_2["綜合活動/2d-III-2<br/>(III/performance)"]
  綜合活動_3a_II_1["綜合活動/3a-II-1<br/>(II/performance)"]
  綜合活動_3a_III_1["綜合活動/3a-III-1<br/>(III/performance)"]
  綜合活動_3b_II_1["綜合活動/3b-II-1<br/>(II/performance)"]
  綜合活動_3b_III_1["綜合活動/3b-III-1<br/>(III/performance)"]
  綜合活動_3c_II_1["綜合活動/3c-II-1<br/>(II/performance)"]
  綜合活動_3c_III_1["綜合活動/3c-III-1<br/>(III/performance)"]
  綜合活動_3d_II_1["綜合活動/3d-II-1<br/>(II/performance)"]
  綜合活動_3d_III_1["綜合活動/3d-III-1<br/>(III/performance)"]
  綜合活動_1a_IV_2["綜合活動/1a-IV-2<br/>(IV/performance)"]
  綜合活動_1b_IV_1["綜合活動/1b-IV-1<br/>(IV/performance)"]
  綜合活動_1b_IV_2["綜合活動/1b-IV-2<br/>(IV/performance)"]
  綜合活動_1c_IV_1["綜合活動/1c-IV-1<br/>(IV/performance)"]
  綜合活動_1c_IV_2["綜合活動/1c-IV-2<br/>(IV/performance)"]
  綜合活動_1c_IV_3["綜合活動/1c-IV-3<br/>(IV/performance)"]
  綜合活動_1d_IV_1["綜合活動/1d-IV-1<br/>(IV/performance)"]
  綜合活動_1d_IV_2["綜合活動/1d-IV-2<br/>(IV/performance)"]
  綜合活動_2a_IV_1["綜合活動/2a-IV-1<br/>(IV/performance)"]
  綜合活動_2a_IV_2["綜合活動/2a-IV-2<br/>(IV/performance)"]
  綜合活動_2a_IV_3["綜合活動/2a-IV-3<br/>(IV/performance)"]
  綜合活動_2b_IV_1["綜合活動/2b-IV-1<br/>(IV/performance)"]
  綜合活動_2b_IV_2["綜合活動/2b-IV-2<br/>(IV/performance)"]
  綜合活動_2c_IV_1["綜合活動/2c-IV-1<br/>(IV/performance)"]
  綜合活動_2c_IV_2["綜合活動/2c-IV-2<br/>(IV/performance)"]
  綜合活動_2d_IV_1["綜合活動/2d-IV-1<br/>(IV/performance)"]
  綜合活動_2d_IV_2["綜合活動/2d-IV-2<br/>(IV/performance)"]
  綜合活動_3a_IV_1["綜合活動/3a-IV-1<br/>(IV/performance)"]
  綜合活動_3a_IV_2["綜合活動/3a-IV-2<br/>(IV/performance)"]
  綜合活動_3b_IV_1["綜合活動/3b-IV-1<br/>(IV/performance)"]
  綜合活動_3c_IV_1["綜合活動/3c-IV-1<br/>(IV/performance)"]
  綜合活動_3c_IV_2["綜合活動/3c-IV-2<br/>(IV/performance)"]
  綜合活動_3d_IV_1["綜合活動/3d-IV-1<br/>(IV/performance)"]
  綜合活動_3d_IV_2["綜合活動/3d-IV-2<br/>(IV/performance)"]
  綜合活動_1b_V_1["綜合活動/1b-V-1<br/>(V/performance)"]
  綜合活動_2a_V_1["綜合活動/2a-V-1<br/>(V/performance)"]
  綜合活動_2b_V_1["綜合活動/2b-V-1<br/>(V/performance)"]
  綜合活動_3a_V_1["綜合活動/3a-V-1<br/>(V/performance)"]
  綜合活動_3b_V_1["綜合活動/3b-V-1<br/>(V/performance)"]
  綜合活動_4a_V_1["綜合活動/4a-V-1<br/>(V/performance)"]
  綜合活動_4b_V_1["綜合活動/4b-V-1<br/>(V/performance)"]
  綜合活動_5a_V_1["綜合活動/5a-V-1<br/>(V/performance)"]
  綜合活動_5b_V_1["綜合活動/5b-V-1<br/>(V/performance)"]
  綜合活動_1c_V_1["綜合活動/1c-V-1<br/>(V/performance)"]
  綜合活動_1c_V_2["綜合活動/1c-V-2<br/>(V/performance)"]
  綜合活動_3c_V_1["綜合活動/3c-V-1<br/>(V/performance)"]
  綜合活動_1a_V_2["綜合活動/1a-V-2<br/>(V/performance)"]
  綜合活動_1b_V_2["綜合活動/1b-V-2<br/>(V/performance)"]
  綜合活動_2a_V_2["綜合活動/2a-V-2<br/>(V/performance)"]
  綜合活動_3a_V_2["綜合活動/3a-V-2<br/>(V/performance)"]
  綜合活動_4b_V_2["綜合活動/4b-V-2<br/>(V/performance)"]
  綜合活動_4c_V_1["綜合活動/4c-V-1<br/>(V/performance)"]
  綜合活動_3b_V_2["綜合活動/3b-V-2<br/>(V/performance)"]
  綜合活動_4a_V_2["綜合活動/4a-V-2<br/>(V/performance)"]
  綜合活動_2b_V_2["綜合活動/2b-V-2<br/>(V/performance)"]
  綜合活動_3b_V_3["綜合活動/3b-V-3<br/>(V/performance)"]
  綜合活動_1b_V_3["綜合活動/1b-V-3<br/>(V/performance)"]
  綜合活動_Aa_II_1 -->|prerequisite| 綜合活動_Aa_III_1
  綜合活動_Aa_III_1 -->|prerequisite| 綜合活動_Aa_IV_1
  綜合活動_Aa_IV_1 -->|prerequisite| 綜合活動_Aa_V_1
  綜合活動_Aa_II_2 -->|prerequisite| 綜合活動_Aa_III_2
  綜合活動_Aa_III_2 -->|prerequisite| 綜合活動_Aa_IV_2
  綜合活動_童Aa_IV_2 -->|prerequisite| 綜合活動_Aa_V_2
  綜合活動_Aa_II_3 -->|prerequisite| 綜合活動_Aa_IV_3
  綜合活動_Aa_IV_3 -->|prerequisite| 綜合活動_Aa_V_3
  綜合活動_Ab_II_1 -->|prerequisite| 綜合活動_Ab_III_1
  綜合活動_Ab_III_1 -->|prerequisite| 綜合活動_Ab_IV_1
  綜合活動_Ab_IV_1 -->|prerequisite| 綜合活動_Ab_V_1
  綜合活動_Ab_II_2 -->|prerequisite| 綜合活動_Ab_III_2
  綜合活動_Ab_III_2 -->|prerequisite| 綜合活動_Ab_IV_2
  綜合活動_家Ab_IV_2 -->|prerequisite| 綜合活動_Ab_V_2
  綜合活動_Ac_II_1 -->|prerequisite| 綜合活動_Ac_III_1
  綜合活動_Ac_III_1 -->|prerequisite| 綜合活動_Ac_IV_1
  綜合活動_Ac_IV_1 -->|prerequisite| 綜合活動_Ac_V_1
  綜合活動_Ac_II_2 -->|prerequisite| 綜合活動_Ac_III_2
  綜合活動_Ac_III_2 -->|prerequisite| 綜合活動_Ac_IV_2
  綜合活動_Ac_IV_2 -->|prerequisite| 綜合活動_Ac_V_2
  綜合活動_Ac_II_3 -->|prerequisite| 綜合活動_Ac_III_3
  綜合活動_Ac_III_3 -->|prerequisite| 綜合活動_Ac_V_3
  綜合活動_Ad_II_1 -->|prerequisite| 綜合活動_Ad_III_1
  綜合活動_Ad_II_2 -->|prerequisite| 綜合活動_Ad_III_2
  綜合活動_Ba_II_1 -->|prerequisite| 綜合活動_Ba_III_1
  綜合活動_Ba_III_1 -->|prerequisite| 綜合活動_Ba_IV_1
  綜合活動_Ba_IV_1 -->|prerequisite| 綜合活動_Ba_V_1
  綜合活動_Ba_II_2 -->|prerequisite| 綜合活動_Ba_III_2
  綜合活動_Ba_III_2 -->|prerequisite| 綜合活動_Ba_IV_2
  綜合活動_Ba_IV_2 -->|prerequisite| 綜合活動_Ba_V_2
  綜合活動_Ba_II_3 -->|prerequisite| 綜合活動_Ba_III_3
  綜合活動_Ba_III_3 -->|prerequisite| 綜合活動_Ba_V_3
  綜合活動_Bb_II_1 -->|prerequisite| 綜合活動_Bb_III_1
  綜合活動_Bb_III_1 -->|prerequisite| 綜合活動_Bb_IV_1
  綜合活動_Bb_IV_1 -->|prerequisite| 綜合活動_Bb_V_1
  綜合活動_Bb_II_2 -->|prerequisite| 綜合活動_Bb_III_2
  綜合活動_Bb_III_2 -->|prerequisite| 綜合活動_童Bb_IV_2
  綜合活動_Bb_IV_2 -->|prerequisite| 綜合活動_Bb_V_2
  綜合活動_Bb_II_3 -->|prerequisite| 綜合活動_Bb_III_3
  綜合活動_Bb_III_3 -->|prerequisite| 綜合活動_Bb_IV_3
  綜合活動_Bb_IV_3 -->|prerequisite| 綜合活動_未Bb_V_3
  綜合活動_Bc_II_1 -->|prerequisite| 綜合活動_Bc_III_1
  綜合活動_Bc_III_1 -->|prerequisite| 綜合活動_Bc_IV_1
  綜合活動_Bc_II_2 -->|prerequisite| 綜合活動_Bc_III_2
  綜合活動_Bc_III_2 -->|prerequisite| 綜合活動_Bc_IV_2
  綜合活動_Bc_II_3 -->|prerequisite| 綜合活動_Bc_III_3
  綜合活動_Bd_II_1 -->|prerequisite| 綜合活動_Bd_III_1
  綜合活動_Bd_II_2 -->|prerequisite| 綜合活動_Bd_III_2
  綜合活動_Ca_II_1 -->|prerequisite| 綜合活動_Ca_III_1
  綜合活動_Ca_III_1 -->|prerequisite| 綜合活動_Ca_IV_1
  綜合活動_Ca_IV_1 -->|prerequisite| 綜合活動_Ca_V_1
  綜合活動_Ca_II_2 -->|prerequisite| 綜合活動_Ca_III_2
  綜合活動_Ca_III_2 -->|prerequisite| 綜合活動_Ca_IV_2
  綜合活動_Ca_IV_2 -->|prerequisite| 綜合活動_Ca_V_2
  綜合活動_Ca_II_3 -->|prerequisite| 綜合活動_Ca_III_3
  綜合活動_Ca_III_3 -->|prerequisite| 綜合活動_童Ca_IV_3
  綜合活動_Ca_IV_3 -->|prerequisite| 綜合活動_Ca_V_3
  綜合活動_Cb_II_1 -->|prerequisite| 綜合活動_Cb_III_1
  綜合活動_Cb_III_1 -->|prerequisite| 綜合活動_Cb_IV_1
  綜合活動_Cb_IV_1 -->|prerequisite| 綜合活動_Cb_V_1
  綜合活動_Cb_II_2 -->|prerequisite| 綜合活動_Cb_III_2
  綜合活動_Cb_III_2 -->|prerequisite| 綜合活動_Cb_IV_2
  綜合活動_Cb_IV_2 -->|prerequisite| 綜合活動_Cb_V_2
  綜合活動_Cb_III_3 -->|prerequisite| 綜合活動_Cb_IV_3
  綜合活動_童Cb_IV_3 -->|prerequisite| 綜合活動_Cb_V_3
  綜合活動_Cc_II_1 -->|prerequisite| 綜合活動_Cc_III_1
  綜合活動_Cc_III_1 -->|prerequisite| 綜合活動_Cc_IV_1
  綜合活動_家Cc_IV_1 -->|prerequisite| 綜合活動_Cc_V_1
  綜合活動_Cc_II_2 -->|prerequisite| 綜合活動_Cc_III_2
  綜合活動_Cc_III_2 -->|prerequisite| 綜合活動_Cc_IV_2
  綜合活動_家Cc_IV_2 -->|prerequisite| 綜合活動_Cc_V_2
  綜合活動_Cc_II_3 -->|prerequisite| 綜合活動_Cc_III_3
  綜合活動_Cd_II_1 -->|prerequisite| 綜合活動_Cd_III_1
  綜合活動_Cd_II_2 -->|prerequisite| 綜合活動_Cd_III_2
  綜合活動_Db_IV_1 -->|prerequisite| 綜合活動_Db_V_1
  綜合活動_Db_IV_2 -->|prerequisite| 綜合活動_Db_V_2
  綜合活動_輔Da_IV_1 -->|prerequisite| 綜合活動_Da_V_1
  綜合活動_家Da_IV_2 -->|prerequisite| 綜合活動_Da_V_2
  綜合活動_家Dc_IV_1 -->|prerequisite| 綜合活動_Dc_V_1
  綜合活動_Db_IV_3 -->|prerequisite| 綜合活動_Db_V_3
  綜合活動_輔Dc_IV_2 -->|prerequisite| 綜合活動_Dc_V_2
  綜合活動_Bb_IV_4 -->|prerequisite| 綜合活動_未Bb_V_4
  綜合活動_Ab_IV_3 -->|prerequisite| 綜合活動_Ab_V_3
  綜合活動_1a_II_1 -->|prerequisite| 綜合活動_1a_III_1
  綜合活動_1a_III_1 -->|prerequisite| 綜合活動_1a_IV_1
  綜合活動_1a_IV_1 -->|prerequisite| 綜合活動_1a_V_1
  綜合活動_1b_II_1 -->|prerequisite| 綜合活動_1b_III_1
  綜合活動_1b_III_1 -->|prerequisite| 綜合活動_1b_IV_1
  綜合活動_1b_IV_1 -->|prerequisite| 綜合活動_1b_V_1
  綜合活動_1c_II_1 -->|prerequisite| 綜合活動_1c_III_1
  綜合活動_1c_III_1 -->|prerequisite| 綜合活動_1c_IV_1
  綜合活動_1c_IV_1 -->|prerequisite| 綜合活動_1c_V_1
  綜合活動_1d_II_1 -->|prerequisite| 綜合活動_1d_III_1
  綜合活動_1d_III_1 -->|prerequisite| 綜合活動_1d_IV_1
  綜合活動_2a_II_1 -->|prerequisite| 綜合活動_2a_III_1
  綜合活動_2a_III_1 -->|prerequisite| 綜合活動_2a_IV_1
  綜合活動_2a_IV_1 -->|prerequisite| 綜合活動_2a_V_1
  綜合活動_2b_II_1 -->|prerequisite| 綜合活動_2b_III_1
  綜合活動_2b_III_1 -->|prerequisite| 綜合活動_2b_IV_1
  綜合活動_2b_IV_1 -->|prerequisite| 綜合活動_2b_V_1
  綜合活動_2b_II_2 -->|prerequisite| 綜合活動_2b_IV_2
  綜合活動_2b_IV_2 -->|prerequisite| 綜合活動_2b_V_2
  綜合活動_2c_II_1 -->|prerequisite| 綜合活動_2c_III_1
  綜合活動_2c_III_1 -->|prerequisite| 綜合活動_2c_IV_1
  綜合活動_2d_II_1 -->|prerequisite| 綜合活動_2d_III_1
  綜合活動_2d_III_1 -->|prerequisite| 綜合活動_2d_IV_1
  綜合活動_2d_II_2 -->|prerequisite| 綜合活動_2d_III_2
  綜合活動_2d_III_2 -->|prerequisite| 綜合活動_2d_IV_2
  綜合活動_3a_II_1 -->|prerequisite| 綜合活動_3a_III_1
  綜合活動_3a_III_1 -->|prerequisite| 綜合活動_3a_IV_1
  綜合活動_3a_IV_1 -->|prerequisite| 綜合活動_3a_V_1
  綜合活動_3b_II_1 -->|prerequisite| 綜合活動_3b_III_1
  綜合活動_3b_III_1 -->|prerequisite| 綜合活動_3b_IV_1
  綜合活動_3b_IV_1 -->|prerequisite| 綜合活動_3b_V_1
  綜合活動_3c_II_1 -->|prerequisite| 綜合活動_3c_III_1
  綜合活動_3c_III_1 -->|prerequisite| 綜合活動_3c_IV_1
  綜合活動_3c_IV_1 -->|prerequisite| 綜合活動_3c_V_1
  綜合活動_3d_II_1 -->|prerequisite| 綜合活動_3d_III_1
  綜合活動_3d_III_1 -->|prerequisite| 綜合活動_3d_IV_1
  綜合活動_1a_IV_2 -->|prerequisite| 綜合活動_1a_V_2
  綜合活動_1b_IV_2 -->|prerequisite| 綜合活動_1b_V_2
  綜合活動_1c_IV_2 -->|prerequisite| 綜合活動_1c_V_2
  綜合活動_2a_IV_2 -->|prerequisite| 綜合活動_2a_V_2
  綜合活動_3a_IV_2 -->|prerequisite| 綜合活動_3a_V_2
