graph LR
  數學_N_1_1["數學/N-1-1<br/>(I/content)"]
  數學_N_1_2["數學/N-1-2<br/>(I/content)"]
  數學_N_1_3["數學/N-1-3<br/>(I/content)"]
  數學_N_1_4["數學/N-1-4<br/>(I/content)"]
  數學_S_1_1["數學/S-1-1<br/>(I/content)"]
  數學_N_1_5["數學/N-1-5<br/>(I/content)"]
  數學_N_2_11["數學/N-2-11<br/>(II/content)"]
  數學_N_2_13["數學/N-2-13<br/>(II/content)"]
  數學_N_2_14["數學/N-2-14<br/>(II/content)"]
  數學_N_1_6["數學/N-1-6<br/>(I/content)"]
  數學_S_1_2["數學/S-1-2<br/>(I/content)"]
  數學_R_1_1["數學/R-1-1<br/>(I/content)"]
  數學_R_1_2["數學/R-1-2<br/>(I/content)"]
  數學_D_1_1["數學/D-1-1<br/>(I/content)"]
  數學_N_2_1["數學/N-2-1<br/>(II/content)"]
  數學_N_2_2["數學/N-2-2<br/>(II/content)"]
  數學_N_2_3["數學/N-2-3<br/>(II/content)"]
  數學_R_2_4["數學/R-2-4<br/>(II/content)"]
  數學_N_2_4["數學/N-2-4<br/>(II/content)"]
  數學_N_2_5["數學/N-2-5<br/>(II/content)"]
  數學_N_2_6["數學/N-2-6<br/>(II/content)"]
  數學_R_2_3["數學/R-2-3<br/>(II/content)"]
  數學_N_2_7["數學/N-2-7<br/>(II/content)"]
  數學_N_2_9["數學/N-2-9<br/>(II/content)"]
  數學_N_3_7["數學/N-3-7<br/>(III/content)"]
  數學_N_2_8["數學/N-2-8<br/>(II/content)"]
  數學_N_2_10["數學/N-2-10<br/>(II/content)"]
  數學_N_3_11["數學/N-3-11<br/>(III/content)"]
  數學_N_2_12["數學/N-2-12<br/>(II/content)"]
  數學_N_3_15["數學/N-3-15<br/>(III/content)"]
  數學_N_3_16["數學/N-3-16<br/>(III/content)"]
  數學_S_2_1["數學/S-2-1<br/>(II/content)"]
  數學_S_2_2["數學/S-2-2<br/>(II/content)"]
  數學_S_4_7["數學/S-4-7<br/>(IV/content)"]
  數學_S_4_8["數學/S-4-8<br/>(IV/content)"]
  數學_D_2_1["數學/D-2-1<br/>(II/content)"]
  數學_S_2_3["數學/S-2-3<br/>(II/content)"]
  數學_S_2_4["數學/S-2-4<br/>(II/content)"]
  數學_S_2_5["數學/S-2-5<br/>(II/content)"]
  數學_R_2_1["數學/R-2-1<br/>(II/content)"]
  數學_R_2_2["數學/R-2-2<br/>(II/content)"]
  數學_N_3_1["數學/N-3-1<br/>(III/content)"]
  數學_N_3_2["數學/N-3-2<br/>(III/content)"]
  數學_N_3_3["數學/N-3-3<br/>(III/content)"]
  數學_N_3_4["數學/N-3-4<br/>(III/content)"]
  數學_N_3_5["數學/N-3-5<br/>(III/content)"]
  數學_N_3_6["數學/N-3-6<br/>(III/content)"]
  數學_R_3_1["數學/R-3-1<br/>(III/content)"]
  數學_N_4_3["數學/N-4-3<br/>(IV/content)"]
  數學_N_3_8["數學/N-3-8<br/>(III/content)"]
  數學_N_3_9["數學/N-3-9<br/>(III/content)"]
  數學_N_3_10["數學/N-3-10<br/>(III/content)"]
  數學_N_3_12["數學/N-3-12<br/>(III/content)"]
  數學_S_3_1["數學/S-3-1<br/>(III/content)"]
  數學_N_3_13["數學/N-3-13<br/>(III/content)"]
  數學_N_3_14["數學/N-3-14<br/>(III/content)"]
  數學_N_4_13["數學/N-4-13<br/>(IV/content)"]
  數學_N_3_17["數學/N-3-17<br/>(III/content)"]
  數學_S_3_2["數學/S-3-2<br/>(III/content)"]
  數學_S_3_3["數學/S-3-3<br/>(III/content)"]
  數學_S_3_4["數學/S-3-4<br/>(III/content)"]
  數學_R_3_2["數學/R-3-2<br/>(III/content)"]
  數學_D_3_1["數學/D-3-1<br/>(III/content)"]
  數學_N_4_1["數學/N-4-1<br/>(IV/content)"]
  數學_N_4_2["數學/N-4-2<br/>(IV/content)"]
  數學_N_4_4["數學/N-4-4<br/>(IV/content)"]
  數學_N_4_5["數學/N-4-5<br/>(IV/content)"]
  數學_N_4_6["數學/N-4-6<br/>(IV/content)"]
  數學_N_4_7["數學/N-4-7<br/>(IV/content)"]
  數學_N_4_8["數學/N-4-8<br/>(IV/content)"]
  數學_N_4_9["數學/N-4-9<br/>(IV/content)"]
  數學_S_4_1["數學/S-4-1<br/>(IV/content)"]
  數學_N_4_10["數學/N-4-10<br/>(IV/content)"]
  數學_N_4_11["數學/N-4-11<br/>(IV/content)"]
  數學_N_4_12["數學/N-4-12<br/>(IV/content)"]
  數學_S_4_2["數學/S-4-2<br/>(IV/content)"]
  數學_S_4_3["數學/S-4-3<br/>(IV/content)"]
  數學_S_4_4["數學/S-4-4<br/>(IV/content)"]
  數學_S_4_5["數學/S-4-5<br/>(IV/content)"]
  數學_S_4_6["數學/S-4-6<br/>(IV/content)"]
  數學_R_4_1["數學/R-4-1<br/>(IV/content)"]
  數學_R_4_2["數學/R-4-2<br/>(IV/content)"]
  數學_R_4_3["數學/R-4-3<br/>(IV/content)"]
  數學_R_4_4["數學/R-4-4<br/>(IV/content)"]
  數學_D_4_1["數學/D-4-1<br/>(IV/content)"]
  數學_N_5_1["數學/N-5-1<br/>(V/content)"]
  數學_N_5_2["數學/N-5-2<br/>(V/content)"]
  數學_R_5_2["數學/R-5-2<br/>(V/content)"]
  數學_N_5_3["數學/N-5-3<br/>(V/content)"]
  數學_N_5_4["數學/N-5-4<br/>(V/content)"]
  數學_N_5_5["數學/N-5-5<br/>(V/content)"]
  數學_N_5_6["數學/N-5-6<br/>(V/content)"]
  數學_N_5_10["數學/N-5-10<br/>(V/content)"]
  數學_N_5_7["數學/N-5-7<br/>(V/content)"]
  數學_N_5_8["數學/N-5-8<br/>(V/content)"]
  數學_N_5_9["數學/N-5-9<br/>(V/content)"]
  數學_N_5_11["數學/N-5-11<br/>(V/content)"]
  數學_N_5_12["數學/N-5-12<br/>(V/content)"]
  數學_N_5_13["數學/N-5-13<br/>(V/content)"]
  數學_N_5_14["數學/N-5-14<br/>(V/content)"]
  數學_N_5_15["數學/N-5-15<br/>(V/content)"]
  數學_N_5_16["數學/N-5-16<br/>(V/content)"]
  數學_S_5_1["數學/S-5-1<br/>(V/content)"]
  數學_S_5_2["數學/S-5-2<br/>(V/content)"]
  數學_S_5_3["數學/S-5-3<br/>(V/content)"]
  數學_S_5_4["數學/S-5-4<br/>(V/content)"]
  數學_S_5_5["數學/S-5-5<br/>(V/content)"]
  數學_S_5_6["數學/S-5-6<br/>(V/content)"]
  數學_S_5_7["數學/S-5-7<br/>(V/content)"]
  數學_R_5_1["數學/R-5-1<br/>(V/content)"]
  數學_R_5_3["數學/R-5-3<br/>(V/content)"]
  數學_D_5_1["數學/D-5-1<br/>(V/content)"]
  數學_n_I_1["數學/n-I-1<br/>(I/performance)"]
  數學_n_I_2["數學/n-I-2<br/>(I/performance)"]
  數學_n_I_3["數學/n-I-3<br/>(I/performance)"]
  數學_n_I_4["數學/n-I-4<br/>(I/performance)"]
  數學_n_I_5["數學/n-I-5<br/>(I/performance)"]
  數學_n_I_6["數學/n-I-6<br/>(I/performance)"]
  數學_n_I_7["數學/n-I-7<br/>(I/performance)"]
  數學_n_I_8["數學/n-I-8<br/>(I/performance)"]
  數學_n_I_9["數學/n-I-9<br/>(I/performance)"]
  數學_s_I_1["數學/s-I-1<br/>(I/performance)"]
  數學_r_I_1["數學/r-I-1<br/>(I/performance)"]
  數學_r_I_2["數學/r-I-2<br/>(I/performance)"]
  數學_r_I_3["數學/r-I-3<br/>(I/performance)"]
  數學_d_I_1["數學/d-I-1<br/>(I/performance)"]
  數學_n_II_1["數學/n-II-1<br/>(II/performance)"]
  數學_n_II_2["數學/n-II-2<br/>(II/performance)"]
  數學_n_II_3["數學/n-II-3<br/>(II/performance)"]
  數學_n_II_4["數學/n-II-4<br/>(II/performance)"]
  數學_n_II_5["數學/n-II-5<br/>(II/performance)"]
  數學_n_II_6["數學/n-II-6<br/>(II/performance)"]
  數學_n_II_7["數學/n-II-7<br/>(II/performance)"]
  數學_n_II_8["數學/n-II-8<br/>(II/performance)"]
  數學_n_II_9["數學/n-II-9<br/>(II/performance)"]
  數學_n_II_10["數學/n-II-10<br/>(II/performance)"]
  數學_s_II_1["數學/s-II-1<br/>(II/performance)"]
  數學_s_II_2["數學/s-II-2<br/>(II/performance)"]
  數學_s_II_3["數學/s-II-3<br/>(II/performance)"]
  數學_s_II_4["數學/s-II-4<br/>(II/performance)"]
  數學_r_II_1["數學/r-II-1<br/>(II/performance)"]
  數學_r_II_2["數學/r-II-2<br/>(II/performance)"]
  數學_r_II_3["數學/r-II-3<br/>(II/performance)"]
  數學_r_II_4["數學/r-II-4<br/>(II/performance)"]
  數學_r_II_5["數學/r-II-5<br/>(II/performance)"]
  數學_d_II_1["數學/d-II-1<br/>(II/performance)"]
  數學_n_III_1["數學/n-III-1<br/>(III/performance)"]
  數學_n_III_2["數學/n-III-2<br/>(III/performance)"]
  數學_n_III_3["數學/n-III-3<br/>(III/performance)"]
  數學_n_III_4["數學/n-III-4<br/>(III/performance)"]
  數學_n_III_5["數學/n-III-5<br/>(III/performance)"]
  數學_n_III_6["數學/n-III-6<br/>(III/performance)"]
  數學_n_III_7["數學/n-III-7<br/>(III/performance)"]
  數學_n_III_8["數學/n-III-8<br/>(III/performance)"]
  數學_n_III_9["數學/n-III-9<br/>(III/performance)"]
  數學_n_III_10["數學/n-III-10<br/>(III/performance)"]
  數學_n_III_11["數學/n-III-11<br/>(III/performance)"]
  數學_n_III_12["數學/n-III-12<br/>(III/performance)"]
  數學_s_III_1["數學/s-III-1<br/>(III/performance)"]
  數學_s_III_2["數學/s-III-2<br/>(III/performance)"]
  數學_s_III_3["數學/s-III-3<br/>(III/performance)"]
  數學_s_III_4["數學/s-III-4<br/>(III/performance)"]
  數學_s_III_5["數學/s-III-5<br/>(III/performance)"]
  數學_s_III_6["數學/s-III-6<br/>(III/performance)"]
  數學_s_III_7["數學/s-III-7<br/>(III/performance)"]
  數學_r_III_1["數學/r-III-1<br/>(III/performance)"]
  數學_r_III_2["數學/r-III-2<br/>(III/performance)"]
  數學_r_III_3["數學/r-III-3<br/>(III/performance)"]
  數學_d_III_1["數學/d-III-1<br/>(III/performance)"]
  數學_d_III_2["數學/d-III-2<br/>(III/performance)"]
  數學_n_IV_1["數學/n-IV-1<br/>(IV/performance)"]
  數學_n_IV_2["數學/n-IV-2<br/>(IV/performance)"]
  數學_n_IV_3["數學/n-IV-3<br/>(IV/performance)"]
  數學_n_IV_4["數學/n-IV-4<br/>(IV/performance)"]
  數學_n_IV_5["數學/n-IV-5<br/>(IV/performance)"]
  數學_n_IV_6["數學/n-IV-6<br/>(IV/performance)"]
  數學_n_IV_7["數學/n-IV-7<br/>(IV/performance)"]
  數學_n_IV_8["數學/n-IV-8<br/>(IV/performance)"]
  數學_n_IV_9["數學/n-IV-9<br/>(IV/performance)"]
  數學_s_IV_1["數學/s-IV-1<br/>(IV/performance)"]
  數學_s_IV_2["數學/s-IV-2<br/>(IV/performance)"]
  數學_s_IV_3["數學/s-IV-3<br/>(IV/performance)"]
  數學_s_IV_4["數學/s-IV-4<br/>(IV/performance)"]
  數學_s_IV_5["數學/s-IV-5<br/>(IV/performance)"]
  數學_s_IV_6["數學/s-IV-6<br/>(IV/performance)"]
  數學_s_IV_7["數學/s-IV-7<br/>(IV/performance)"]
  數學_s_IV_8["數學/s-IV-8<br/>(IV/performance)"]
  數學_s_IV_9["數學/s-IV-9<br/>(IV/performance)"]
  數學_s_IV_10["數學/s-IV-10<br/>(IV/performance)"]
  數學_s_IV_11["數學/s-IV-11<br/>(IV/performance)"]
  數學_s_IV_12["數學/s-IV-12<br/>(IV/performance)"]
  數學_s_IV_13["數學/s-IV-13<br/>(IV/performance)"]
  數學_s_IV_14["數學/s-IV-14<br/>(IV/performance)"]
  數學_s_IV_15["數學/s-IV-15<br/>(IV/performance)"]
  數學_s_IV_16["數學/s-IV-16<br/>(IV/performance)"]
  數學_g_IV_1["數學/g-IV-1<br/>(IV/performance)"]
  數學_g_IV_2["數學/g-IV-2<br/>(IV/performance)"]
  數學_a_IV_1["數學/a-IV-1<br/>(IV/performance)"]
  數學_a_IV_2["數學/a-IV-2<br/>(IV/performance)"]
  數學_a_IV_3["數學/a-IV-3<br/>(IV/performance)"]
  數學_a_IV_4["數學/a-IV-4<br/>(IV/performance)"]
  數學_a_IV_5["數學/a-IV-5<br/>(IV/performance)"]
  數學_a_IV_6["數學/a-IV-6<br/>(IV/performance)"]
  數學_f_IV_1["數學/f-IV-1<br/>(IV/performance)"]
  數學_f_IV_2["數學/f-IV-2<br/>(IV/performance)"]
  數學_f_IV_3["數學/f-IV-3<br/>(IV/performance)"]
  數學_d_IV_1["數學/d-IV-1<br/>(IV/performance)"]
  數學_d_IV_2["數學/d-IV-2<br/>(IV/performance)"]
  數學_n_V_1["數學/n-V-1<br/>(V/performance)"]
  數學_n_V_2["數學/n-V-2<br/>(V/performance)"]
  數學_n_V_3["數學/n-V-3<br/>(V/performance)"]
  數學_n_V_4["數學/n-V-4<br/>(V/performance)"]
  數學_n_V_5["數學/n-V-5<br/>(V/performance)"]
  數學_n_V_6["數學/n-V-6<br/>(V/performance)"]
  數學_n_V_7["數學/n-V-7<br/>(V/performance)"]
  數學_n_V_8["數學/n-V-8<br/>(V/performance)"]
  數學_s_V_1["數學/s-V-1<br/>(V/performance)"]
  數學_s_V_2["數學/s-V-2<br/>(V/performance)"]
  數學_g_V_1["數學/g-V-1<br/>(V/performance)"]
  數學_g_V_2["數學/g-V-2<br/>(V/performance)"]
  數學_g_V_3["數學/g-V-3<br/>(V/performance)"]
  數學_g_V_4["數學/g-V-4<br/>(V/performance)"]
  數學_g_V_5["數學/g-V-5<br/>(V/performance)"]
  數學_a_V_1["數學/a-V-1<br/>(V/performance)"]
  數學_a_V_2["數學/a-V-2<br/>(V/performance)"]
  數學_a_V_3["數學/a-V-3<br/>(V/performance)"]
  數學_a_V_4["數學/a-V-4<br/>(V/performance)"]
  數學_f_V_1["數學/f-V-1<br/>(V/performance)"]
  數學_f_V_2["數學/f-V-2<br/>(V/performance)"]
  數學_f_V_3["數學/f-V-3<br/>(V/performance)"]
  數學_f_V_4["數學/f-V-4<br/>(V/performance)"]
  數學_f_V_5["數學/f-V-5<br/>(V/performance)"]
  數學_f_V_6["數學/f-V-6<br/>(V/performance)"]
  數學_f_V_7["數學/f-V-7<br/>(V/performance)"]
  數學_f_V_8["數學/f-V-8<br/>(V/performance)"]
  數學_f_V_9["數學/f-V-9<br/>(V/performance)"]
  數學_d_V_1["數學/d-V-1<br/>(V/performance)"]
  數學_d_V_2["數學/d-V-2<br/>(V/performance)"]
  數學_d_V_3["數學/d-V-3<br/>(V/performance)"]
  數學_d_V_4["數學/d-V-4<br/>(V/performance)"]
  數學_d_V_5["數學/d-V-5<br/>(V/performance)"]
  數學_d_V_6["數學/d-V-6<br/>(V/performance)"]
  數學_d_V_7["數學/d-V-7<br/>(V/performance)"]
  數學_N_1_1 -->|prerequisite| 數學_N_2_1
  數學_N_2_1 -->|prerequisite| 數學_N_3_1
  數學_N_3_1 -->|prerequisite| 數學_N_4_1
  數學_N_4_1 -->|prerequisite| 數學_N_5_1
  數學_N_1_2 -->|prerequisite| 數學_N_2_2
  數學_N_2_2 -->|prerequisite| 數學_N_3_2
  數學_N_3_2 -->|prerequisite| 數學_N_4_2
  數學_N_4_2 -->|prerequisite| 數學_N_5_2
  數學_N_1_3 -->|prerequisite| 數學_N_2_3
  數學_N_2_3 -->|prerequisite| 數學_N_3_3
  數學_N_3_3 -->|prerequisite| 數學_N_4_3
  數學_N_4_3 -->|prerequisite| 數學_N_5_3
  數學_N_1_4 -->|prerequisite| 數學_N_2_4
  數學_N_2_4 -->|prerequisite| 數學_N_3_4
  數學_N_3_4 -->|prerequisite| 數學_N_4_4
  數學_N_4_4 -->|prerequisite| 數學_N_5_4
  數學_S_1_1 -->|prerequisite| 數學_S_2_1
  數學_S_2_1 -->|prerequisite| 數學_S_3_1
  數學_S_3_1 -->|prerequisite| 數學_S_4_1
  數學_S_4_1 -->|prerequisite| 數學_S_5_1
  數學_N_1_5 -->|prerequisite| 數學_N_2_5
  數學_N_2_5 -->|prerequisite| 數學_N_3_5
  數學_N_3_5 -->|prerequisite| 數學_N_4_5
  數學_N_4_5 -->|prerequisite| 數學_N_5_5
  數學_N_2_11 -->|prerequisite| 數學_N_3_11
  數學_N_3_11 -->|prerequisite| 數學_N_4_11
  數學_N_4_11 -->|prerequisite| 數學_N_5_11
  數學_N_2_13 -->|prerequisite| 數學_N_3_13
  數學_N_3_13 -->|prerequisite| 數學_N_4_13
  數學_N_4_13 -->|prerequisite| 數學_N_5_13
  數學_N_2_14 -->|prerequisite| 數學_N_3_14
  數學_N_3_14 -->|prerequisite| 數學_N_5_14
  數學_N_1_6 -->|prerequisite| 數學_N_2_6
  數學_N_2_6 -->|prerequisite| 數學_N_3_6
  數學_N_3_6 -->|prerequisite| 數學_N_4_6
  數學_N_4_6 -->|prerequisite| 數學_N_5_6
  數學_S_1_2 -->|prerequisite| 數學_S_2_2
  數學_S_2_2 -->|prerequisite| 數學_S_3_2
  數學_S_3_2 -->|prerequisite| 數學_S_4_2
  數學_S_4_2 -->|prerequisite| 數學_S_5_2
  數學_R_1_1 -->|prerequisite| 數學_R_2_1
  數學_R_2_1 -->|prerequisite| 數學_R_3_1
  數學_R_3_1 -->|prerequisite| 數學_R_4_1
  數學_R_4_1 -->|prerequisite| 數學_R_5_1
  數學_R_1_2 -->|prerequisite| 數學_R_2_2
  數學_R_2_2 -->|prerequisite| 數學_R_3_2
  數學_R_3_2 -->|prerequisite| 數學_R_4_2
  數學_R_4_2 -->|prerequisite| 數學_R_5_2
  數學_D_1_1 -->|prerequisite| 數學_D_2_1
  數學_D_2_1 -->|prerequisite| 數學_D_3_1
  數學_D_3_1 -->|prerequisite| 數學_D_4_1
  數學_D_4_1 -->|prerequisite| 數學_D_5_1
  數學_R_2_4 -->|prerequisite| 數學_R_4_4
  數學_R_2_3 -->|prerequisite| 數學_R_4_3
  數學_R_4_3 -->|prerequisite| 數學_R_5_3
  數學_N_2_7 -->|prerequisite| 數學_N_3_7
  數學_N_3_7 -->|prerequisite| 數學_N_4_7
  數學_N_4_7 -->|prerequisite| 數學_N_5_7
  數學_N_2_9 -->|prerequisite| 數學_N_3_9
  數學_N_3_9 -->|prerequisite| 數學_N_4_9
  數學_N_4_9 -->|prerequisite| 數學_N_5_9
  數學_N_2_8 -->|prerequisite| 數學_N_3_8
  數學_N_3_8 -->|prerequisite| 數學_N_4_8
  數學_N_4_8 -->|prerequisite| 數學_N_5_8
  數學_N_2_10 -->|prerequisite| 數學_N_3_10
  數學_N_3_10 -->|prerequisite| 數學_N_4_10
  數學_N_4_10 -->|prerequisite| 數學_N_5_10
  數學_N_2_12 -->|prerequisite| 數學_N_3_12
  數學_N_3_12 -->|prerequisite| 數學_N_4_12
  數學_N_4_12 -->|prerequisite| 數學_N_5_12
  數學_N_3_15 -->|prerequisite| 數學_N_5_15
  數學_N_3_16 -->|prerequisite| 數學_N_5_16
  數學_S_4_7 -->|prerequisite| 數學_S_5_7
  數學_S_2_3 -->|prerequisite| 數學_S_3_3
  數學_S_3_3 -->|prerequisite| 數學_S_4_3
  數學_S_4_3 -->|prerequisite| 數學_S_5_3
  數學_S_2_4 -->|prerequisite| 數學_S_3_4
  數學_S_3_4 -->|prerequisite| 數學_S_4_4
  數學_S_4_4 -->|prerequisite| 數學_S_5_4
  數學_S_2_5 -->|prerequisite| 數學_S_4_5
  數學_S_4_5 -->|prerequisite| 數學_S_5_5
  數學_S_4_6 -->|prerequisite| 數學_S_5_6
  數學_n_I_1 -->|prerequisite| 數學_n_II_1
  數學_n_II_1 -->|prerequisite| 數學_n_III_1
  數學_n_III_1 -->|prerequisite| 數學_n_IV_1
  數學_n_IV_1 -->|prerequisite| 數學_n_V_1
  數學_n_I_2 -->|prerequisite| 數學_n_II_2
  數學_n_II_2 -->|prerequisite| 數學_n_III_2
  數學_n_III_2 -->|prerequisite| 數學_n_IV_2
  數學_n_IV_2 -->|prerequisite| 數學_n_V_2
  數學_n_I_3 -->|prerequisite| 數學_n_II_3
  數學_n_II_3 -->|prerequisite| 數學_n_III_3
  數學_n_III_3 -->|prerequisite| 數學_n_IV_3
  數學_n_IV_3 -->|prerequisite| 數學_n_V_3
  數學_n_I_4 -->|prerequisite| 數學_n_II_4
  數學_n_II_4 -->|prerequisite| 數學_n_III_4
  數學_n_III_4 -->|prerequisite| 數學_n_IV_4
  數學_n_IV_4 -->|prerequisite| 數學_n_V_4
  數學_n_I_5 -->|prerequisite| 數學_n_II_5
  數學_n_II_5 -->|prerequisite| 數學_n_III_5
  數學_n_III_5 -->|prerequisite| 數學_n_IV_5
  數學_n_IV_5 -->|prerequisite| 數學_n_V_5
  數學_n_I_6 -->|prerequisite| 數學_n_II_6
  數學_n_II_6 -->|prerequisite| 數學_n_III_6
  數學_n_III_6 -->|prerequisite| 數學_n_IV_6
  數學_n_IV_6 -->|prerequisite| 數學_n_V_6
  數學_n_I_7 -->|prerequisite| 數學_n_II_7
  數學_n_II_7 -->|prerequisite| 數學_n_III_7
  數學_n_III_7 -->|prerequisite| 數學_n_IV_7
  數學_n_IV_7 -->|prerequisite| 數學_n_V_7
  數學_n_I_8 -->|prerequisite| 數學_n_II_8
  數學_n_II_8 -->|prerequisite| 數學_n_III_8
  數學_n_III_8 -->|prerequisite| 數學_n_IV_8
  數學_n_IV_8 -->|prerequisite| 數學_n_V_8
  數學_n_I_9 -->|prerequisite| 數學_n_II_9
  數學_n_II_9 -->|prerequisite| 數學_n_III_9
  數學_n_III_9 -->|prerequisite| 數學_n_IV_9
  數學_s_I_1 -->|prerequisite| 數學_s_II_1
  數學_s_II_1 -->|prerequisite| 數學_s_III_1
  數學_s_III_1 -->|prerequisite| 數學_s_IV_1
  數學_s_IV_1 -->|prerequisite| 數學_s_V_1
  數學_r_I_1 -->|prerequisite| 數學_r_II_1
  數學_r_II_1 -->|prerequisite| 數學_r_III_1
  數學_r_I_2 -->|prerequisite| 數學_r_II_2
  數學_r_II_2 -->|prerequisite| 數學_r_III_2
  數學_r_I_3 -->|prerequisite| 數學_r_II_3
  數學_r_II_3 -->|prerequisite| 數學_r_III_3
  數學_d_I_1 -->|prerequisite| 數學_d_II_1
  數學_d_II_1 -->|prerequisite| 數學_d_III_1
  數學_d_III_1 -->|prerequisite| 數學_d_IV_1
  數學_d_IV_1 -->|prerequisite| 數學_d_V_1
  數學_n_II_10 -->|prerequisite| 數學_n_III_10
  數學_s_II_2 -->|prerequisite| 數學_s_III_2
  數學_s_III_2 -->|prerequisite| 數學_s_IV_2
  數學_s_IV_2 -->|prerequisite| 數學_s_V_2
  數學_s_II_3 -->|prerequisite| 數學_s_III_3
  數學_s_III_3 -->|prerequisite| 數學_s_IV_3
  數學_s_II_4 -->|prerequisite| 數學_s_III_4
  數學_s_III_4 -->|prerequisite| 數學_s_IV_4
  數學_s_III_5 -->|prerequisite| 數學_s_IV_5
  數學_s_III_6 -->|prerequisite| 數學_s_IV_6
  數學_s_III_7 -->|prerequisite| 數學_s_IV_7
  數學_d_III_2 -->|prerequisite| 數學_d_IV_2
  數學_d_IV_2 -->|prerequisite| 數學_d_V_2
  數學_g_IV_1 -->|prerequisite| 數學_g_V_1
  數學_g_IV_2 -->|prerequisite| 數學_g_V_2
  數學_a_IV_1 -->|prerequisite| 數學_a_V_1
  數學_a_IV_2 -->|prerequisite| 數學_a_V_2
  數學_a_IV_3 -->|prerequisite| 數學_a_V_3
  數學_a_IV_4 -->|prerequisite| 數學_a_V_4
  數學_f_IV_1 -->|prerequisite| 數學_f_V_1
  數學_f_IV_2 -->|prerequisite| 數學_f_V_2
  數學_f_IV_3 -->|prerequisite| 數學_f_V_3
